<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>

    <style>
        @page {
            margin: 24px 22px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #111827;
        }

        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
            margin-bottom: 14px;
        }

        .title {
            font-size: 19px;
            font-weight: bold;
            color: #0f172a;
            margin-bottom: 3px;
        }

        .subtitle {
            font-size: 11px;
            color: #64748b;
        }

        .meta {
            width: 100%;
            margin-top: 10px;
            border-collapse: collapse;
        }

        .meta td {
            padding: 4px 6px;
            background: #f8fafc;
            border: 1px solid #e5e7eb;
            font-size: 9px;
        }

        .meta strong {
            color: #334155;
        }

        table.report {
            width: 100%;
            border-collapse: collapse;
        }

        table.report th {
            background: #eff6ff;
            color: #1e3a8a;
            border: 1px solid #cbd5e1;
            padding: 6px;
            font-size: 8.5px;
            text-align: left;
        }

        table.report td {
            border: 1px solid #e5e7eb;
            padding: 5px;
            font-size: 8.5px;
            vertical-align: top;
        }

        table.report tr:nth-child(even) td {
            background: #fafafa;
        }

        .empty {
            padding: 24px;
            text-align: center;
            color: #64748b;
            border: 1px dashed #cbd5e1;
            background: #f8fafc;
        }

        .footer {
            margin-top: 14px;
            font-size: 8px;
            color: #64748b;
            text-align: right;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">{{ $title }}</div>
        <div class="subtitle">{{ $subtitle }}</div>

        <table class="meta">
            <tr>
                <td><strong>Branch:</strong> {{ $meta['branch'] ?? 'All branches' }}</td>
                <td><strong>Date From:</strong> {{ $meta['date_from'] ?? '-' }}</td>
                <td><strong>Date To:</strong> {{ $meta['date_to'] ?? '-' }}</td>
                <td><strong>Generated:</strong> {{ $generatedAt->format('d M Y h:i A') }}</td>
            </tr>
        </table>
    </div>

    @if(count($rows))
        <table class="report">
            <thead>
                <tr>
                    @foreach($headings as $heading)
                        <th>{{ $heading }}</th>
                    @endforeach
                </tr>
            </thead>

            <tbody>
                @foreach($rows as $row)
                    <tr>
                        @foreach($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="empty">
            No records found for selected filters.
        </div>
    @endif

    <div class="footer">
        Generated by Smart Pharmacy
    </div>
</body>
</html>